FROM node:24-slim
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy full project
COPY . .

# Expose port
EXPOSE 3000

# Use nodemon or ts-node for hot reload
CMD ["npm", "run", "dev"]
