FROM node:24.12.0-trixie-slim

WORKDIR /app

RUN printf "ignore-scripts=true\n" > .npmrc

COPY package*.json ./

RUN npm ci

# run allowed scripts only (better-sqlite3)
RUN npx allow-scripts run

COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev"]
